[build]
  publish = "."

# REDIRECCIONES PARA NEGOCIOS (más específicas primero)
[[redirects]]
  from = "/castelar/negocios/*"
  to = "/castelar/negocios/:splat"
  status = 200

[[redirects]]
  from = "/ituzaingo/negocios/*"
  to = "/ituzaingo/negocios/:splat"
  status = 200

[[redirects]]
  from = "/moron/negocios/*"
  to = "/moron/negocios/:splat"
  status = 200

[[redirects]]
  from = "/ciudadela/negocios/*"
  to = "/ciudadela/negocios/:splat"
  status = 200

[[redirects]]
  from = "/merlo/negocios/*"
  to = "/merlo/negocios/:splat"
  status = 200

[[redirects]]
  from = "/haedo/negocios/*"
  to = "/haedo/negocios/:splat"
  status = 200

[[redirects]]
  from = "/ramos-mejia/negocios/*"
  to = "/ramos-mejia/negocios/:splat"
  status = 200

# REDIRECCIONES PARA CADA LOCALIDAD
[[redirects]]
  from = "/castelar/*"
  to = "/castelar/index.html"
  status = 200

[[redirects]]
  from = "/ituzaingo/*"
  to = "/ituzaingo/index.html"
  status = 200

[[redirects]]
  from = "/moron/*"
  to = "/moron/index.html"
  status = 200

[[redirects]]
  from = "/ciudadela/*"
  to = "/ciudadela/index.html"
  status = 200

[[redirects]]
  from = "/merlo/*"
  to = "/merlo/index.html"
  status = 200

[[redirects]]
  from = "/haedo/*"
  to = "/haedo/index.html"
  status = 200

[[redirects]]
  from = "/ramos-mejia/*"
  to = "/ramos-mejia/index.html"
  status = 200

# CATCH-ALL para la página principal (menos específica al final)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"